CREATE TABLE hacker
(
    id SERIAL PRIMARY KEY NOT NULL,
    email VARCHAR(30) DEFAULT NULL NOT NULL,
    location VARCHAR(30) DEFAULT NULL NOT NULL,
    fb_oauth_access_token VARCHAR(60) DEFAULT NULL NOT NULL
);
CREATE UNIQUE INDEX unique_email ON hacker (email);
